// Copyright (c) 2017-2021 Uber Technologies Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package internal

import (
	s "go.uber.org/cadence/.gen/go/shared"
)

// Priority is a client hint about how latency-sensitive the internal tasks
// generated by a workflow decision (e.g. a timer or a child workflow) are.
// The server may use this to deprioritize execution of tasks that opt into a
// lower priority such as PriorityAsync.
//
// The zero value (PriorityUnset) leaves the priority unspecified, and the
// server-side default behavior is used.
type Priority int

const (
	// PriorityUnset leaves the priority unspecified (server default is used).
	// This is the zero value and results in an omitted priority field.
	PriorityUnset Priority = iota
	// PriorityHigh marks the task as latency-sensitive / high priority.
	PriorityHigh
	// PriorityDefault marks the task with the default priority.
	PriorityDefault
	// PriorityLow marks the task as low priority.
	PriorityLow
	// PriorityAsync marks the task as async, opting into deprioritized
	// ("best effort") execution by the server.
	PriorityAsync
)

// toThriftPtr converts the public Priority into the generated thrift
// TaskPriority pointer. PriorityUnset maps to nil so the field is omitted.
func (p Priority) toThriftPtr() *s.TaskPriority {
	switch p {
	case PriorityUnset:
		return nil
	case PriorityHigh:
		return s.TaskPriorityHigh.Ptr()
	case PriorityDefault:
		return s.TaskPriorityDefault.Ptr()
	case PriorityLow:
		return s.TaskPriorityLow.Ptr()
	case PriorityAsync:
		return s.TaskPriorityAsync.Ptr()
	default:
		return nil
	}
}

// timerOptions holds the resolved options for a timer.
type timerOptions struct {
	priority Priority
}

// TimerOption is a functional option that customizes a timer created via
// NewTimer or Sleep.
type TimerOption func(*timerOptions)

// WithPriority sets the priority of a timer created via NewTimer or Sleep.
func WithPriority(priority Priority) TimerOption {
	return func(o *timerOptions) {
		o.priority = priority
	}
}

// resolveTimerOptions applies all the supplied options and returns the result.
func resolveTimerOptions(options []TimerOption) timerOptions {
	var opts timerOptions
	for _, opt := range options {
		if opt != nil {
			opt(&opts)
		}
	}
	return opts
}

// withTimerPriority returns a child workflow Context carrying the timer
// priority. It is used to thread the priority through the existing interceptor
// chain without changing any exported interceptor signature.
func withTimerPriority(ctx Context, p Priority) Context {
	return WithValue(ctx, timerPriorityContextKey, p)
}

// getTimerPriority returns the timer priority carried by ctx, defaulting to
// PriorityUnset when none is present.
func getTimerPriority(ctx Context) Priority {
	if v := ctx.Value(timerPriorityContextKey); v != nil {
		if p, ok := v.(Priority); ok {
			return p
		}
	}
	return PriorityUnset
}
